### PR TITLE
fixed issue#86 Show rejected transaction with detailed message

### PR DESCRIPTION
**Pull request by iamyates**
1. changed update rejected tx strategy: 
previous: query from DB
current:  query from RPC

2. since there's no such method ( get_transaction) in CKB-Ruby-SDK, so I used HTTP gem

3. add unit tests and VCR fixture ( which mocks http request)

### CODE REVIEW

**Comment by Keith-CY** [comment]
> since there's no such method ( get_transaction) in CKB-Ruby-SDK, so I used HTTP gem

I see the `get_transaction(tx_hash)` demo in readme(https://github.com/nervosnetwork/ckb-sdk-ruby#usage), doesn't it work?

**Comment by iamyates** [comment]
> > since there's no such method ( get_transaction) in CKB-Ruby-SDK, so I used HTTP gem
> 
> I see the `get_transaction(tx_hash)` demo in readme(https://github.com/nervosnetwork/ckb-sdk-ruby#usage), doesn't it work?

Sorry for my inaccurate description.

The method (`get_transaction`) exits in CKB-Ruby-SDK, however it doesn't show the information that I needed.  It gives result like : 

```
> api = CKB::API.new(host: ENV["CKB_NODE_URL"], timeout_config: { open_timeout: 1, read_timeout: 3, write_timeout: 1 })
=> #<API@http://localhost:8114>

> api.get_transaction '0xed2049c21ffccfcd26281d60f8f77ff117adb9df9d3f8cbe5fe86e893c66d359'
=> #<CKB::Types::TransactionWithStatus:0x000055dc78e945d0 
    @transaction=nil, 
    @tx_status=#<CKB::Types::TxStatus:0x000055dc78e94990 @block_hash=nil, @status="rejected">>
```

However what I want is the "rejected reason", such as ( via `curl` command), which is missing in the `CKB::API`, shown as below:  

```
{
    "jsonrpc":"2.0",
    "result":{
        "transaction":null,
        "tx_status":{
            "block_hash":null,
            "reason":"{\"type\":\"Resolve\",\"description\":\"Resolve failed Dead(OutPoint(0x8dbf552ea6278ee765421e288acbf0489c8d55172954a10d8fec2257a76e713f00000000))\"}",
            "status":"rejected"
        }
    },
    "id":42
}
```

so I have to use the CURL-RPC way. 

In the future, I think I can add some PR to the CKB-RUBY-SDK by add more information.

**Comment by iamyates** [comment]
> > since there's no such method ( get_transaction) in CKB-Ruby-SDK, so I used HTTP gem
> 
> I see the `get_transaction(tx_hash)` demo in readme(https://github.com/nervosnetwork/ckb-sdk-ruby#usage), doesn't it work?

My mistake, I re-pushed my code.

**Comment by iamyates** [comment]
@Keith-CY  please notice that the api `/api/v1/transactions/` has changed, added a new field named `detailed_message`, e.g.:

for `rejected transaction`, it returns the raw message from RPC:  `{"type":"Resolve","description":"Resolve failed Dead(OutPoint(0x8dbf552ea6278ee765421e288acbf0489c8d55172954a10d8fec2257a76e713f00000000))"}`

image

for other transaction ( pending, proposed, commited ), it returns `'This transaction is not rejected.'` shown as below: 

image

**Comment by Keith-CY** [comment]
@ShiningRay please have a review

**Review by ShiningRay — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
