### PR TITLE
fixed issue#59: show since field explicitly

### PR DESCRIPTION
**Pull request by iamyates**
added since field to interface:   /api/v1/transactions/0xb70b810b675e1cbbba1b53665017a46ef2389641a41ed55ce4f3ee6fcd04b2f4

image

added these field: 
```
                    "since": {
                        "raw": "0x0000000000000000",                   // hex value of since 
                        "median_timestamp": "1574246410846"    // api will always return this value.  use it when you want to. 
                    }
```

# How to update the existing data

please follow these steps when deploy : 

1.stop the node-processor process:   `bundle exec ruby lib/ckb_block_node_processor.rb`
2.`rake db:migrate` 
3.go to the rails app folder, then `RAILS_ENV=production rails console`  , then run this code:  `Block.update_block_median_timestamp <block_number>`, this command will update all the existing `blocks` , by adding a `median_timestamp` value to the table. 
4.after step3, let's start `bundle exec ruby lib/ckb_block_node_processor.rb`

### CODE REVIEW

**Comment by Keith-CY** [comment]
CI failed

**Comment by iamyates** [comment]
failed unit test is fixed. please review, thanks.

**Comment by Keith-CY** [comment]
Conflicted

**Comment by iamyates** [comment]
> Conflicted

sorry for waiting, resolved

**Review by ShiningRay — APPROVED** [review]

**Pull request merged**
