### PR TITLE
Clean up cache

### PR DESCRIPTION
**Pull request by iamyates**
1.removed ListCacheService and related code
2.removed most of Rails.cache.realize block
3.removed cached_find for app/models
4.removed useless unit tests

all the unit tests are passed.  please review, thanks!

### CODE REVIEW

**Comment by Keith-CY** [comment]
Will this update impact online services?
Or the new cache mechanism will be added before this update is deployed to production environments

**Comment by ShiningRay** [comment]
Please create a "next" branch along with "develop" and merge this to "next" branch

**Comment by iamyates** [comment]
> Please create a "next" branch along with "develop" and merge this to "next" branch

OK, the new PR is:  https://github.com/nervosnetwork/ckb-explorer/pull/1024  ,  merging into "next" branch

**Comment by Keith-CY** [comment]
Is this PR closed for the new one being merged into `next` branch? If yes, there's an <kbd>edit</kbd> button to update the base branch
image
image

**Pull request closed without merging**
