### PR TITLE
feat(server): add cell input data tests and api

### PR DESCRIPTION
**Pull request by shaojunda**

### CODE REVIEW

**Comment by duanyytop** [comment]
Why some commit contents is same as old pr.

**Comment by shaojunda** [comment]
not the same, please look at commit body

**Comment by shaojunda** [comment]
Because the development and testing process between different apis is very close, but the details are different. so, description is the same but I put details in the commit body. @duanyytop

**Comment by shaojunda** [comment]
The reason why the details are placed inside commit body is commit description has length limit.

**Comment by duanyytop** [comment]
I see. I mean same commit content could not make other developers know what to do. 

It's not a big question.

**Pull request merged**
